# Generated by Django 3.1.3 on 2022-05-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220502_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='companyName',
            new_name='orderCustomer',
        ),
        migrations.RenameField(
            model_name='truckcustomer',
            old_name='companyName',
            new_name='orderCompany',
        ),
    ]
